Repository brazil-data-cube/bdc-collection-builder, pull requests merged in 2019-11, with the labels that each got.

#16 [celery] Fix sentinel publish task
  bdc_scripts/celery/worker.py
  bdc_scripts/radcor/landsat/tasks.py
  bdc_scripts/radcor/sentinel/publish.py
  bdc_scripts/radcor/sentinel/tasks.py
  docker-compose.yml
  setup.py
Labels: bug

#24 fixed generate_cogs to produce valid cogs
  bdc_scripts/core/utils.py
Labels: invalid

#25 Fix sentinel catalog metadata
  bdc_scripts/radcor/sentinel/publish.py
Labels: enhancement

#27 Close #26 - Restart sentinel task atm-correction
  bdc_scripts/radcor/sentinel/tasks.py
  bdc_scripts/radcor/utils.py
Labels: bug

#28 Force sentinel output folder on publish to L2A
  bdc_scripts/radcor/sentinel/publish.py
Labels: invalid

#33 Improve radcor activity on celery execution
  bdc_scripts/celery/worker.py
  bdc_scripts/models/base_sql.py
  bdc_scripts/radcor/__init__.py
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/forms.py
  bdc_scripts/radcor/landsat/tasks.py
  bdc_scripts/radcor/models/__init__.py
  bdc_scripts/radcor/models/activity.py
  bdc_scripts/radcor/models/activity_history.py
  bdc_scripts/radcor/sentinel/clients.py
  bdc_scripts/radcor/sentinel/tasks.py
  bdc_scripts/radcor/utils.py
  migrations/versions/88f1744b1d76_.py
Labels: enhancement

#36 List tasks from celery
  bdc_scripts/celery/utils.py
  bdc_scripts/radcor/controller.py
Labels: enhancement

#38 Fix Connection Error, Download LC1 and minor validations
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/controller.py
  bdc_scripts/radcor/sentinel/download.py
  bdc_scripts/radcor/sentinel/tasks.py
  bdc_scripts/radcor/utils.py
Labels: bug
