Repository brazil-data-cube/bdc-collection-builder, pull requests merged in 2019-10, with the labels that each got.

#8 Fix multthread TIFF crash
  rc_maestro/rc_maestro.py
Labels: bug

#9 updated S2 dirs & multprocessing
  rc_maestro/rc_maestro.py
Labels: bug, enhancement

#10 Development
  ds_source/maestro.py
  rc_maestro/rc_maestro.py
Labels: enhancement
