Repository brazil-data-cube/bdc-collection-builder, pull requests merged in 2020-01, with the labels that each got.

#62 Celery rearch recent safe dirs and undo id format
  bdc_scripts/radcor/base_task.py
  bdc_scripts/radcor/sentinel/correction.py
Labels: bug

#63 Add cube generation - celery
  bdc_scripts/blueprint.py
  bdc_scripts/celery/__init__.py
  bdc_scripts/celery/worker.py
  bdc_scripts/config.py
  bdc_scripts/datastorm/__init__.py
  bdc_scripts/datastorm/business.py
  bdc_scripts/datastorm/controller.py
  bdc_scripts/datastorm/forms.py
  bdc_scripts/datastorm/maestro.py
  bdc_scripts/datastorm/models/__init__.py
  bdc_scripts/datastorm/models/activity.py
  bdc_scripts/datastorm/models/activity_history.py
  bdc_scripts/datastorm/parsers.py
  bdc_scripts/datastorm/tasks.py
  bdc_scripts/datastorm/utils.py
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/models/activity.py
  bdc_scripts/radcor/sentinel/publish.py
  migrations/env.py
  migrations/versions/7ae7f1df8bd6_add_datastorm_activities.py
  setup.py
Labels: enhancement

#65 Persist radcor collections on AWS
  bdc_scripts/__init__.py
  bdc_scripts/config.py
  bdc_scripts/core/utils.py
  bdc_scripts/datastorm/models/activity.py
  bdc_scripts/db.py
  bdc_scripts/radcor/forms.py
  bdc_scripts/radcor/landsat/publish.py
  bdc_scripts/radcor/models/activity.py
  bdc_scripts/radcor/sentinel/download.py
  bdc_scripts/radcor/sentinel/publish.py
  bdc_scripts/radcor/sentinel/tasks.py
  bdc_scripts/radcor/utils.py
  docker-compose.yml
  setup.py
Labels: enhancement

#68 Catalog Landsat Collections on multiple databases
  bdc_scripts/__init__.py
  bdc_scripts/core/utils.py
  bdc_scripts/radcor/landsat/publish.py
  bdc_scripts/radcor/landsat/tasks.py
  bdc_scripts/radcor/utils.py
  migrations/versions/962a0f21f6e8_add_bdc_db_activities_v1.0.py
Labels: enhancement

#70 Disable upload of l1 collections to AWS
  bdc_scripts/config.py
  bdc_scripts/core/utils.py
  bdc_scripts/radcor/landsat/publish.py
  bdc_scripts/radcor/sentinel/publish.py
  bdc_scripts/radcor/sentinel/tasks.py
  bdc_scripts/radcor/utils.py
Labels: enhancement

#71 Name convention for TOA and DN collections
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/landsat/publish.py
  bdc_scripts/radcor/sentinel/tasks.py
Labels: enhancement

#72 Fix sentinel ignore TOA on aws
  bdc_scripts/radcor/sentinel/publish.py
Labels: bug

#74 hotfix always extract sentinel SAFE zips
  bdc_scripts/core/utils.py
Labels: bug

#79 Minor fixes on radcor
  bdc_scripts/celery/__init__.py
  bdc_scripts/core/utils.py
  bdc_scripts/radcor/__init__.py
  bdc_scripts/radcor/base_task.py
  bdc_scripts/radcor/landsat/publish.py
  bdc_scripts/radcor/landsat/tasks.py
  bdc_scripts/radcor/sentinel/publish.py
  bdc_scripts/radcor/sentinel/tasks.py
Labels: bug

#80 Fix collection tile creation on radcor
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/landsat/publish.py
  bdc_scripts/radcor/sentinel/publish.py
  bdc_scripts/radcor/utils.py
  build.sh
Labels: bug

#83 Remove useless code on celery tasks
  bdc_scripts/celery/utils.py
  bdc_scripts/celery/worker.py
  bdc_scripts/datastorm/__init__.py
Labels: bug

#86 Rollback session dispose - It causing session deadlock
  bdc_scripts/celery/__init__.py
  bdc_scripts/db.py
  bdc_scripts/version.py
  docker-compose.yml
Labels: bug

#89 Close #88 - Fix landsat link LGN value
  bdc_scripts/radcor/landsat/download.py
  bdc_scripts/radcor/utils.py
Labels: bug

#90 Fix landsat atm task chain
  bdc_scripts/radcor/utils.py
Labels: bug

#82 Feature/authentication
  .gitignore
  bdc_scripts/config.py
  bdc_scripts/datastorm/controller.py
  bdc_scripts/radcor/controller.py
Labels: enhancement

#91 Feature/get statistics
  bdc_scripts/__init__.py
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/controller.py
Labels: enhancement

#94 Close #45 - Task Retry
  bdc_scripts/celery/__init__.py
  bdc_scripts/config.py
  bdc_scripts/radcor/base_task.py
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/landsat/tasks.py
  bdc_scripts/radcor/sentinel/download.py
  bdc_scripts/radcor/sentinel/tasks.py
  setup.py
Labels: bug, enhancement

#93 change oauth scope
  bdc_scripts/radcor/business.py
  bdc_scripts/radcor/controller.py
Labels: bug, enhancement
