Repository brazil-data-cube/bdc-collection-builder, pull requests merged in 2020-04, with the labels that each got.

#143 Fix sen2cor output directory and minor changes
  bdc_collection_builder/collections/base_task.py
  bdc_collection_builder/collections/landsat/publish.py
  bdc_collection_builder/collections/sentinel/correction.py
  bdc_collection_builder/collections/sentinel/publish.py
  bdc_collection_builder/collections/utils.py
  sen2cor/rc_sen2cor.py
Labels: bug

#145 Minor changes - EarthExplorer as default provider and Improve Restart task
  bdc_collection_builder/collections/business.py
  bdc_collection_builder/collections/controller.py
  bdc_collection_builder/collections/forms.py
  bdc_collection_builder/collections/landsat/download.py
  bdc_collection_builder/collections/landsat/tasks.py
Labels: enhancement

#147 Close #146 - Set ONDA as primary external provider
  bdc_collection_builder/collections/sentinel/onda.py
  bdc_collection_builder/collections/sentinel/tasks.py
  secrets.json
Labels: enhancement

#149 Sentinel-2 Harmonization & fix L8 harm & fix sen2cor output
  bdc_collection_builder/collections/business.py
  bdc_collection_builder/collections/controller.py
  bdc_collection_builder/collections/landsat/harmonization.py
  bdc_collection_builder/collections/landsat/publish.py
  bdc_collection_builder/collections/landsat/tasks.py
  bdc_collection_builder/collections/nbar.py
  bdc_collection_builder/collections/sentinel/correction.py
  bdc_collection_builder/collections/sentinel/harmonization.py
  bdc_collection_builder/collections/sentinel/publish.py
  bdc_collection_builder/collections/sentinel/tasks.py
  bdc_collection_builder/collections/sentinel/utils.py
  bdc_collection_builder/collections/utils.py
  sen2cor/rc_sen2cor.py
Labels: enhancement

#150 Documentation review on branch b-0.2 - DEPLOY.rst
  DEPLOY.rst
  bdc_collection_builder/collections/controller.py
  doc/sphinx/conf.py
  doc/sphinx/deploy.rst
  doc/sphinx/index.rst
Labels: documentation

#151 Add option to refresh view on publish
  bdc_collection_builder/collections/controller.py
  bdc_collection_builder/collections/landsat/tasks.py
  bdc_collection_builder/collections/sentinel/tasks.py
  bdc_collection_builder/collections/utils.py
  bdc_collection_builder/config.py
  setup.py
Labels: enhancement

#152 Improve doc - CONFIG.rst
  CONFIG.rst
  DEPLOY.rst
  doc/sphinx/config.rst
  doc/sphinx/index.rst
Labels: documentation

#154 0.2.0 Doc review: README About
  README.rst
Labels: documentation
