Repository brazil-data-cube/bdc-collection-builder, pull requests merged in 2020-02, with the labels that each got.

#95 #52 - Download sentinel from CREODIAS when scene is offline
  bdc_scripts/radcor/sentinel/download.py
  bdc_scripts/radcor/sentinel/tasks.py
  secrets.json
Labels: enhancement

#98 fix search with paginator
  bdc_collection_builder/collections/controller.py
Labels: bug

#102 Minor changes - Fix download landsat and dummy value on cog files
  bdc_collection_builder/collections/business.py
  bdc_collection_builder/collections/landsat/download.py
  bdc_collection_builder/core/utils.py
  bdc_collection_builder/version.py
  docker-compose.yml
Labels: bug

#105 Remove workdir scene on landsat espa science
  bdc_collection_builder/collections/business.py
  bdc_collection_builder/collections/landsat/publish.py
  bdc_collection_builder/collections/landsat/tasks.py
  espa-science/rc_espa.py
Labels: bug

#107 Fix nodata on cogs
  bdc_collection_builder/core/utils.py
Labels: bug

#110 Fix minor bugs - dependency error
  bdc_collection_builder/collections/landsat/tasks.py
  bdc_collection_builder/collections/sentinel/tasks.py
  bdc_collection_builder/version.py
  setup.py
Labels: bug

#112 #Close 77 and #Close 108
  bdc_collection_builder/collections/landsat/publish.py
  bdc_collection_builder/collections/sentinel/publish.py
  bdc_collection_builder/collections/utils.py
Labels: enhancement

#114 Set retry download and upload on noconnection
  .dockerignore
  .gitignore
  bdc_collection_builder/collections/landsat/tasks.py
  bdc_collection_builder/collections/sentinel/download.py
  bdc_collection_builder/collections/sentinel/tasks.py
Labels: bug

#117 bugfix publish LC8DN match pattern array
  bdc_collection_builder/collections/landsat/publish.py
Labels: bug

#119 Repository structure change and documentation on source code
  .gitignore
  INSTALL.rst
  MANIFEST.in
  README.rst
  bdc_collection_builder/__init__.py
  bdc_collection_builder/__main__.py
  bdc_collection_builder/blueprint.py
  bdc_collection_builder/celery/__init__.py
  bdc_collection_builder/celery/cache.py
  bdc_collection_builder/celery/utils.py
  bdc_collection_builder/celery/worker.py
  bdc_collection_builder/cli.py
  bdc_collection_builder/collections/__init__.py
  bdc_collection_builder/collections/base_task.py
  bdc_collection_builder/collections/business.py
  bdc_collection_builder/collections/controller.py
  bdc_collection_builder/collections/forms.py
  bdc_collection_builder/collections/landsat/download.py
  bdc_collection_builder/collections/landsat/publish.py
  bdc_collection_builder/collections/landsat/tasks.py
  bdc_collection_builder/collections/models/__init__.py
  bdc_collection_builder/collections/models/activity.py
  bdc_collection_builder/collections/models/activity_history.py
  bdc_collection_builder/collections/sentinel/__init__.py
  bdc_collection_builder/collections/sentinel/clients.py
  bdc_collection_builder/collections/sentinel/correction.py
  bdc_collection_builder/collections/sentinel/download.py
  bdc_collection_builder/collections/sentinel/publish.py
  bdc_collection_builder/collections/sentinel/tasks.py
  bdc_collection_builder/collections/utils.py
  bdc_collection_builder/config.py
  bdc_collection_builder/core/__init__.py
  bdc_collection_builder/core/utils.py
  bdc_collection_builder/db.py
  bdc_collection_builder/version.py
  doc/sphinx/Makefile
  doc/sphinx/_static/bdc_collection_builder.min.css
  doc/sphinx/api.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  doc/sphinx/installation.rst
  doc/sphinx/license.rst
  doc/sphinx/make.bat
  migrations/versions/7ae7f1df8bd6_add_datastorm_activities.py
  run-test.sh
  setup.py
Labels: documentation

#120 Close #51 - Add fixture for local development
  bdc_collection_builder/__init__.py
  bdc_collection_builder/cli.py
  bdc_collection_builder/collections/models/activity.py
  bdc_collection_builder/collections/models/activity_history.py
  bdc_collection_builder/config.py
  bdc_collection_builder/fixtures/__init__.py
  bdc_collection_builder/fixtures/cli.py
  bdc_collection_builder/fixtures/data/collections.json
  bdc_collection_builder/fixtures/data/composite_functions.json
  bdc_collection_builder/fixtures/data/grs_schemas.json
  bdc_collection_builder/fixtures/data/tiles.json
  docker/Dockerfile
  migrations/env.py
  migrations/versions/15c5dd54c390_add_bdc_db_v0_2_0.py
  migrations/versions/962a0f21f6e8_add_bdc_db_activities_v1.0.py
  setup.py
Labels: documentation

#121 Sen2cor & LaSRC documentation - Setting up
  RUNNING.rst
Labels: documentation

#122 Close #76 - Improve documentation workflow
  .gitignore
  RUNNING.rst
  bdc_collection_builder/cli.py
  bdc_collection_builder/config.py
  doc/sphinx/index.rst
  doc/sphinx/running.rst
  docker-compose.yml
Labels: documentation

#124 #76 - improve doc running and move fixtures to bdc-db
  RUNNING.rst
  bdc_collection_builder/cli.py
  bdc_collection_builder/config.py
  bdc_collection_builder/fixtures/__init__.py
  bdc_collection_builder/fixtures/cli.py
  bdc_collection_builder/fixtures/data/collections.json
  bdc_collection_builder/fixtures/data/composite_functions.json
  bdc_collection_builder/fixtures/data/grs_schemas.json
  bdc_collection_builder/fixtures/data/tiles.json
  docker-compose.yml
  setup.py
Labels: documentation

#127 Close #126 - Fix TIFF validation utility
  bdc_collection_builder/collections/utils.py
Labels: bug
